FROM php:8.4-fpm-alpine
RUN apk update && apk add gmp-dev libpq-dev su-exec netcat-openbsd
RUN docker-php-ext-install pdo_mysql pdo_pgsql gmp
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_HOME /app/.composer

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set entrypoint
ENTRYPOINT ["entrypoint.sh"]
CMD ["php-fpm"]
