version: '3.8'

services:

  eve_srp_db:
    container_name: eve_srp_db
    image: mariadb:10.11
    restart: unless-stopped

    # IMPORTANT: Adjust volume path for Synology NAS
    # Example: /volume1/docker/eve-srp/db:/var/lib/mysql
    volumes:
      - eve_srp_db_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-eve_srp}

    ports:
      - "${DB_PORT:-33061}:3306"

    networks:
      - eve-srp

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

  eve_srp_php:
    container_name: eve_srp_php

    # IMPORTANT: Replace with your Docker Hub image
    image: ysu53/dsla-eve-srp-php:1.0

    restart: unless-stopped

    depends_on:
      eve_srp_db:
        condition: service_healthy

    # IMPORTANT: Adjust volume paths for Synology NAS
    # Only mount if you need to override files or access logs
    volumes:
      # Optional: Mount only if you need custom configuration
      # - /volume1/docker/eve-srp/config:/app/config

      # Storage for cache and logs (required)
      - eve_srp_storage:/app/storage

      # Optional: Mount logs for monitoring
      # - /volume1/docker/eve-srp/logs:/app/storage/logs

    # Note: /app/web/dist contains frontend build results from the image
    # No volume mount needed - files are baked into the image

    working_dir: /app

    networks:
      - eve-srp

    dns:
      - 8.8.8.8
      - 8.8.4.4

    environment:
      # Database Connection
      EVE_SRP_DB_URL: mysql://${DB_USER}:${DB_PASSWORD}@eve_srp_db/${DB_NAME:-eve_srp}

      # EVE SSO Configuration
      EVE_SRP_SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      EVE_SRP_SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
      EVE_SRP_SSO_REDIRECT_URI: ${SSO_REDIRECT_URI}

      # Provider Configuration
      EVE_SRP_PROVIDER: ${PROVIDER:-EveSrp\Provider\Implementation\EsiProvider}
      EVE_SRP_ROLE_GLOBAL_ADMIN: ${ROLE_GLOBAL_ADMIN:-global-admin}

      # Application Environment
      EVE_SRP_ENV: ${APP_ENV:-prod}
      EVE_SRP_SESSION_SECURE: ${SESSION_SECURE:-1}
      EVE_SRP_REQUIRE_GROUP_FOR_LOGIN: ${REQUIRE_GROUP:-false}

      # Customization
      EVE_SRP_APP_TITLE: ${APP_TITLE:-Ship Replacement Program}
      EVE_SRP_APP_LOGO: ${APP_LOGO:-/static/logo-srp.png}
      EVE_SRP_APP_LOGO_ALT: ${APP_LOGO_ALT:-SRP Logo}
      EVE_SRP_HTTP_USER_AGENT: ${HTTP_USER_AGENT:-EVE-SRP (https://github.com/tkhamez/eve-srp)}
      EVE_SRP_ZKILLBOARD_URL: ${ZKILLBOARD_URL:-https://zkillboard.com}

      # Modifier Calculation
      EVE_SRP_MODIFIER_CALCULATION: ${MODIFIER_CALCULATION:-sequentially}

      # Optional Texts
      EVE_SRP_LOGIN_HINT: ${LOGIN_HINT:-}
      EVE_SRP_FOOTER_TEXT: ${FOOTER_TEXT:-}
      EVE_SRP_SUBMIT_DETAILS_PLACEHOLDER: ${SUBMIT_DETAILS_PLACEHOLDER:-}
      EVE_SRP_SUBMIT_DETAILS_HELP: ${SUBMIT_DETAILS_HELP:-}

      # ESI Provider - Group Configuration
      EVE_SRP_PROVIDER_ESI_SUBMITTER_ALLIANCES: ${ESI_SUBMITTER_ALLIANCES:-}
      EVE_SRP_PROVIDER_ESI_SUBMITTER_CORPORATIONS: ${ESI_SUBMITTER_CORPORATIONS:-}
      EVE_SRP_PROVIDER_ESI_REVIEW_CHARACTERS: ${ESI_REVIEW_CHARACTERS:-}
      EVE_SRP_PROVIDER_ESI_REVIEW_CORPORATIONS: ${ESI_REVIEW_CORPORATIONS:-}
      EVE_SRP_PROVIDER_ESI_PAY_CHARACTERS: ${ESI_PAY_CHARACTERS:-}
      EVE_SRP_PROVIDER_ESI_PAY_CORPORATIONS: ${ESI_PAY_CORPORATIONS:-}
      EVE_SRP_PROVIDER_ESI_ADMIN_CHARACTERS: ${ESI_ADMIN_CHARACTERS:-}
      EVE_SRP_PROVIDER_ESI_GLOBAL_ADMIN_CHARACTERS: ${ESI_GLOBAL_ADMIN_CHARACTERS:-}

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s

  eve_srp_http:
    container_name: eve_srp_http

    # IMPORTANT: Replace with your Docker Hub image
    image: nginx:1

    restart: unless-stopped

    depends_on:
      eve_srp_php:
        condition: service_healthy

    # Note: Nginx configuration is baked into the image
    # Static files (/dist/) are also in the image

    ports:
      - "${HTTP_PORT:-9000}:80"

    networks:
      - eve-srp

    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  eve-srp:
    driver: bridge

volumes:
  # Database data
  eve_srp_db_data:
    driver: local
    # For Synology, you can specify exact path:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /volume1/docker/eve-srp/db

  # Application storage (cache, logs, doctrine)
  eve_srp_storage:
    driver: local
    # For Synology, you can specify exact path:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /volume1/docker/eve-srp/storage
